* The role and contribution of Singapore in the progress of ASEAN as a regional organization.

** Roles
   The roles of Singapore is changing in the different history period. Generally we can divide them in to 3 part. Watching Pay attention and Leading.

*** Watching(before 1968)
    Singapore is the confounder with Indonesia Malaysia, Philippines, and Thailand to established the ASEAN organization.
    
    In the beginning of the establishing of the ASEAN. Singapore doubt the purperse of the ASEAN. Because this area have many failure attempts.
    Such as ASA and MAFHLDNDO.ASA was the first regional grouping based on an exclusively Southeast Asian initiative. 
    And the 1968 Sabah Dispute nearly destroy the exist of ASEAN.

*** Pay attention（1968-1997）
On 18 July 1967, Britain announced its plans to withdraw its troops from
Singapore by the mid-1970s.1 Six months later, the deadline was brought forward
to 1971.2 The sudden pull-out of British forces presented serious problems to
Singaporeâs defence and economic security. 

So Singapore started to pay more and more attention to cooperate with ASEAN to
stable the economy and safety.

*** Leading（after 1997 - future）
   Singapore recover fast from the Asia financial crisis.

   Singapore plans to drive e-commerce and other wings of the digital economy within the region, when it assumes chairmanship of Asean next year.

** Contribution
  The contribution of Singapore can be divided into 2 part. Economy and Area Security.

*** Economy(Relationship to China)
    Indonesia and Singapore start normalize the China in mid-1991 after a thirteen-year lapse, and the ASEAN organization has
begun treating China in an official way. The leaders at the 1992 ASEAN summit invited China to the next AMM in Manlia, although
this is a reserved and restricted invitation. The good relationship with China is also the foundation for the ASEAN-China Free Trade
Area came into effect on 1 January 2010.

*** Area Security(vietnam cambodia invasion)

The invasion and the decade-long occupation of Cambodia by Vietnamese forces
from December 1978 posed the most serious security challenge to ASEAN
since its inception. Not only did ASEAN see Vietnam’s action as a blatant
violation of its norms, but the Cambodia conflict also tested intra-ASEAN
relations, thereby threatening its emerging culture of unity and consensus.

Singapore as a small country surrounded by big countries like cambodia. So Singapore
showed worried about the military actions taken by vietnam.

Singapore’s position was more or less similar, although the Republic, with its advanced defence production
capability, was in a much better position than Malaysia to provide logistics
support as well as armaments to its threatened neighbour.


Marc Frey, Ronald W. Pruessen, Tai Yong Tan The Transformation of Southeast Asia , Retrieved from https://books.google.com.sg/books?id=a51sBgAAQBAJ&pg=PA251&lpg=PA251&dq=asa+maphilindo&source=bl&ots=BFa33AIJOs&sig=rhUvQ0G6vTRBNoSeGey8PRpoXsw&hl=en&sa=X&ved=0ahUKEwjauteD_r3WAhWBwI8KHU4RDo4Q6AEIQTAI#v=onepage&q=asa%20maphilindo&f=false 250

ANTOLIK, M. (1992). ASEAN's Singapore Rendezvous: Just Another Summit? Contemporary Southeast Asia, 14(2), 142-153. Retrieved from http://www.jstor.org/stable/25798147 page148

1. Pull-out in middle 1970âs. (1967, July 19). The Straits Times, p. 1. Retrieved from NewspaperSG.

Amitiav Acharya Constructing a Security Community in Southeast Asia, 80. Retrieved from https://fmc90.files.wordpress.com/2010/05/constructing-a-security-in-asean.pdf

15 This was confirmed by General Saiyud Kerdphol, the former Supreme Commander
of Royal Thai Armed Forces, in a personal interview with the author. According to
General Saiyud, both Malaysia and Singapore were informally involved, along with
the USA, in a plan to provide contingency assistance to Thailand in the event of a
major escalation of the Cambodia conflict spilling over into Thailand. This plan,
worked out by General Saiyud himself and dubbed ‘Joint Logistics Plan’ (JLP),
envisaged provision of armaments, including ‘common items’ such as ammunition
and 105 mm and 155 mm guns, by Singapore and Malaysia from the latter’s own
stocks. According to General Saiyud, steps were taken to ‘identify and mark’ such
items for emergency shipment. The JLP was a ‘classified’ plan worked out at the
‘highest level’ of the governments of the countries involved. It was to be activated
in the event of a major threat to Thailand, not minor skirmishes on the border, but
if Thailand faced the prospect of an open attack by Vietnam backed by the Soviet
Union, resulting in seizure of Thai territory. Personal interview, Bangkok, 26 June
1989 and 28 July 1989.

http://www.straitstimes.com/business/spore-to-lead-e-commerce-push-in-region-as-asean-chair